export const personalTopics = [
  { category: "leadership", hook: "Funcionário não é família. E empresa que diz isso geralmente quer cobrar afeto no lugar de gestão.", lesson: "Família não tem meta, contrato nem demissão. Relação profissional saudável precisa de respeito, clareza e reciprocidade — não culpa emocional.", action: "Empresa deve ser família ou isso é manipulação?", hashtags: "#Liderança #GestãoDePessoas #Empreendedorismo #CaioFidelis" },
  { category: "leadership", hook: "Líder que precisa ser amado pelo time quase sempre evita a conversa que o time precisa ouvir.", lesson: "Buscar aprovação torna o feedback frouxo, adia decisões e premia comportamento errado. Respeito dura mais que popularidade.", action: "Um bom líder precisa ser querido?", hashtags: "#Liderança #Gestão #CulturaEmpresarial #CaioFidelis" },
  { category: "leadership", hook: "Seu melhor funcionário pode ser o motivo de sua equipe continuar mediana.", lesson: "Quando uma pessoa resolve tudo, ninguém desenvolve autonomia e o dono chama dependência de alta performance.", action: "Talento individual fortalece ou enfraquece o time?", hashtags: "#Liderança #Equipe #GestãoEmpresarial #CaioFidelis" },
  { category: "leadership", hook: "Funcionário desmotivado nem sempre precisa de incentivo. Às vezes precisa de consequência.", lesson: "Empresa que transforma toda falta de entrega em problema emocional ensina que responsabilidade é opcional.", action: "Cobrança firme desmotiva ou profissionaliza?", hashtags: "#Liderança #GestãoDePessoas #AltaPerformance #CaioFidelis" },
  { category: "leadership", hook: "O dono que resolve tudo não tem uma equipe. Tem uma plateia remunerada.", lesson: "Centralizar decisão parece controle, mas treina adultos competentes a esperar autorização para qualquer movimento.", action: "Seu time tem autonomia de verdade?", hashtags: "#Liderança #Delegação #Empreendedorismo #CaioFidelis" },
  { category: "leadership", hook: "Cultura boa não é ambiente sem conflito. É ambiente onde o conflito não vira covardia.", lesson: "Silêncio, indireta e concordância falsa protegem o clima por um dia e destroem a confiança por meses.", action: "Sua empresa evita conflito ou sabe enfrentá-lo?", hashtags: "#CulturaEmpresarial #Liderança #Gestão #CaioFidelis" },

  { category: "business", hook: "Sócio 50/50 parece justo até o primeiro impasse sério.", lesson: "Dividir tudo igualmente sem definir desempate, função e saída transforma amizade em paralisia empresarial.", action: "Sociedade igualitária é justa ou perigosa?", hashtags: "#SociedadeEmpresarial #Negócios #Empreendedorismo #CaioFidelis" },
  { category: "business", hook: "Faturamento alto é uma ótima maneira de esconder uma empresa pobre.", lesson: "Receita impressiona. Caixa, margem e dependência do dono revelam se existe negócio ou apenas movimento caro.", action: "O que vale mais: faturamento ou liberdade operacional?", hashtags: "#Negócios #GestãoFinanceira #Empreendedorismo #CaioFidelis" },
  { category: "business", hook: "Empresa que não funciona sem o dono não é patrimônio. É emprego sem férias.", lesson: "Se toda decisão, cliente e crise volta para você, o CNPJ só sofisticou sua dependência.", action: "Você construiu uma empresa ou criou seu próprio cargo?", hashtags: "#Empreendedorismo #GestãoEmpresarial #Negócios #CaioFidelis" },
  { category: "business", hook: "Quem mistura dinheiro da empresa com dinheiro pessoal ainda não tem empresa.", lesson: "Tem uma conta bancária confusa sustentando decisões emocionais e uma falsa sensação de lucro.", action: "Separar contas é detalhe contábil ou maturidade?", hashtags: "#FinançasEmpresariais #Negócios #Gestão #CaioFidelis" },
  { category: "business", hook: "Crescer rápido demais quebra empresas que pareciam saudáveis.", lesson: "Mais clientes amplificam atraso, retrabalho, contratação errada e falta de caixa. Escala não cura desorganização.", action: "Toda empresa deveria querer crescer rápido?", hashtags: "#Crescimento #Empreendedorismo #GestãoEmpresarial #CaioFidelis" },
  { category: "business", hook: "O empresário que comemora agenda cheia talvez não tenha percebido que construiu uma prisão.", lesson: "Ocupação constante pode significar preço errado, ausência de processo e incapacidade de delegar — não sucesso.", action: "Agenda lotada é status ou alerta?", hashtags: "#Empreendedorismo #Produtividade #Negócios #CaioFidelis" },

  { category: "law", hook: "Advogado que promete atendimento humanizado não está se posicionando. Está prometendo o mínimo.", lesson: "Ser educado, responder e ouvir o cliente não diferencia ninguém. Posicionamento exige uma escolha que o mercado reconheça.", action: "Atendimento humanizado ainda diferencia um escritório?", hashtags: "#Advocacia #Posicionamento #GestãoJurídica #CaioFidelis" },
  { category: "law", hook: "OAB não transforma advogado em empresário. E muitos descobrem isso tarde demais.", lesson: "Conhecimento técnico entrega o serviço. Gestão, processo e posicionamento constroem o escritório.", action: "Faculdade prepara alguém para gerir um escritório?", hashtags: "#Advocacia #GestãoJurídica #EmpreendedorismoJurídico #CaioFidelis" },
  { category: "law", hook: "Advogado que aceita todo tipo de caso não tem escritório completo. Tem medo de dizer não.", lesson: "Generalismo sem estratégia dilui reputação, comunicação e eficiência. Escolher também é uma forma de crescer.", action: "Especialização limita ou fortalece?", hashtags: "#Advocacia #PosicionamentoJurídico #GestãoJurídica #CaioFidelis" },
  { category: "law", hook: "Cobrar barato não democratiza seu trabalho quando torna seu escritório inviável.", lesson: "Preço incapaz de sustentar estrutura, estudo e atendimento prejudica primeiro o cliente que você prometeu ajudar.", action: "Honorário baixo é acesso ou falta de gestão?", hashtags: "#Advocacia #Honorários #GestãoJurídica #CaioFidelis" },
  { category: "law", hook: "O cliente não contrata o advogado mais técnico. Contrata aquele cuja competência consegue perceber.", lesson: "Conhecimento invisível não gera confiança. Clareza, autoridade e experiência percebida fazem parte do serviço.", action: "Competência basta quando ninguém consegue enxergá-la?", hashtags: "#Advocacia #Autoridade #MarketingJurídico #CaioFidelis" },
  { category: "law", hook: "Escritório que depende de indicação não tem estratégia. Tem sorte recorrente.", lesson: "Indicação é excelente canal, mas péssimo plano único. O que você não controla também pode desaparecer sem aviso.", action: "Indicação é modelo de crescimento?", hashtags: "#Advocacia #GestãoJurídica #Crescimento #CaioFidelis" },

  { category: "mindset", hook: "Você não está sem tempo. Está protegendo prioridades que não admite ter.", lesson: "Agenda revela valores com mais honestidade que discurso. O que sempre fica para depois nunca foi prioridade de verdade.", action: "Falta tempo ou falta coragem de escolher?", hashtags: "#Disciplina #Produtividade #DesenvolvimentoPessoal #CaioFidelis" },
  { category: "mindset", hook: "Humildade demais pode ser apenas medo de assumir ambição em público.", lesson: "Diminuir o próprio objetivo para não incomodar ninguém não é virtude. É terceirizar sua vida para a opinião alheia.", action: "Ambição declarada incomoda por quê?", hashtags: "#Ambição #Mentalidade #Crescimento #CaioFidelis" },
  { category: "mindset", hook: "Quem espera confiança para começar escolheu não começar.", lesson: "Confiança costuma aparecer depois da exposição, da prática e do erro — não antes deles.", action: "Você precisa acreditar ou precisa agir?", hashtags: "#Coragem #Disciplina #DesenvolvimentoPessoal #CaioFidelis" },
  { category: "mindset", hook: "Trabalhar muito não compensa continuar escolhendo mal.", lesson: "Esforço aplicado na direção errada apenas leva você mais rápido para um resultado que não queria.", action: "Persistir sempre é uma virtude?", hashtags: "#Mentalidade #Estratégia #Produtividade #CaioFidelis" },
  { category: "mindset", hook: "A pessoa que culpa o algoritmo geralmente ainda não criou nada que mereça ser compartilhado.", lesson: "Distribuição importa, mas conteúdo genérico não vira relevante apenas porque foi publicado com frequência.", action: "O algoritmo limita ou revela?", hashtags: "#Conteúdo #Posicionamento #Mentalidade #CaioFidelis" },
  { category: "mindset", hook: "Estabilidade é confortável até o dia em que outra pessoa decide tirá-la de você.", lesson: "Renda, cargo e rotina parecem seguros quando dependem de decisões que não estão nas suas mãos.", action: "Estabilidade existe ou é apenas sensação?", hashtags: "#Carreira #Mentalidade #Empreendedorismo #CaioFidelis" },

  { category: "strategy", hook: "Processo demais também é desorganização — só que documentada.", lesson: "Quando toda exceção vira regra e toda tarefa ganha aprovação, a empresa chama lentidão de controle.", action: "Seu processo protege ou atrapalha?", hashtags: "#Processos #Gestão #Eficiência #CaioFidelis" },
  { category: "strategy", hook: "Reunião sem decisão é procrastinação com testemunhas.", lesson: "Se ninguém sai com responsável, prazo e próximo movimento, vocês apenas adiaram o problema em grupo.", action: "Quantas reuniões desta semana mudaram algo?", hashtags: "#Gestão #Produtividade #Liderança #CaioFidelis" },
  { category: "strategy", hook: "Planejamento anual costuma ser o lugar onde empresas guardam decisões que não pretendem executar.", lesson: "Meta sem responsável, ritmo de revisão e consequência vira decoração corporativa.", action: "Seu planejamento orienta a semana ou só ocupa um arquivo?", hashtags: "#Planejamento #Estratégia #GestãoEmpresarial #CaioFidelis" },
  { category: "strategy", hook: "Automatizar bagunça só faz o erro acontecer mais rápido.", lesson: "Tecnologia multiplica o processo que encontra. Antes da ferramenta, alguém precisa decidir o que deveria acontecer.", action: "Sua empresa precisa de automação ou de clareza?", hashtags: "#Automação #Processos #Gestão #CaioFidelis" },
  { category: "strategy", hook: "Indicador demais é uma forma sofisticada de não olhar para o número que dói.", lesson: "Painel cheio permite escolher a métrica mais confortável. Boa gestão define poucos números que exigem decisão.", action: "Você mede para decidir ou para apresentar?", hashtags: "#Indicadores #Gestão #Estratégia #CaioFidelis" },
  { category: "strategy", hook: "Contratar mais gente para um processo ruim é financiar o caos.", lesson: "Equipe maior não corrige responsabilidade confusa, retrabalho e ausência de padrão. Apenas aumenta o custo do problema.", action: "Falta gente ou sobra desorganização?", hashtags: "#Processos #GestãoDePessoas #Eficiência #CaioFidelis" },

  { category: "sales", hook: "Cliente que pede desconto antes de entender o valor não é oportunidade. É risco.", lesson: "Se a conversa começa pelo preço, você aceitou ser comparado como commodity antes de construir qualquer diferença.", action: "Todo cliente merece negociação?", hashtags: "#Negociação #Vendas #Negócios #CaioFidelis" },
  { category: "sales", hook: "Proposta sem data de decisão é orçamento grátis para o cliente comparar.", lesson: "Enviar um PDF e esperar resposta entrega o controle da conversa e transforma seu trabalho em referência para o concorrente.", action: "Você envia proposta ou conduz decisão?", hashtags: "#Negociação #ProcessoComercial #Vendas #CaioFidelis" },
  { category: "sales", hook: "O cliente não sumiu. Ele apenas não viu motivo suficiente para responder.", lesson: "Mensagem que pergunta 'alguma novidade?' transfere todo o esforço para quem já estava indeciso.", action: "Sua última mensagem merecia resposta?", hashtags: "#Relacionamento #Negociação #Vendas #CaioFidelis" },
  { category: "sales", hook: "Desconto fácil é confissão de que o primeiro preço não era sério.", lesson: "Quando o valor cai sem mudança de escopo ou compromisso, você ensina o cliente a desconfiar de todas as cifras seguintes.", action: "Negociar é ceder ou trocar?", hashtags: "#Preço #Negociação #Vendas #CaioFidelis" },
  { category: "sales", hook: "Quem tenta atender todo mundo termina relevante para ninguém.", lesson: "Mensagem genérica evita rejeição, mas também impede identificação. Posicionamento forte perde curiosos para ganhar clientes certos.", action: "Quem sua oferta deveria excluir?", hashtags: "#Posicionamento #Negócios #Vendas #CaioFidelis" },
  { category: "sales", hook: "Mais leads não salvam uma empresa que trata mal os que já recebeu.", lesson: "Antes de comprar mais atenção, meça demora, abandono e qualidade do atendimento. Volume amplifica tudo — inclusive incompetência.", action: "Falta oportunidade ou sobra desperdício?", hashtags: "#Atendimento #GestãoComercial #Vendas #CaioFidelis" }
];
